<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDZO4Cfd\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDZO4Cfd/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDZO4Cfd.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDZO4Cfd\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDZO4Cfd\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'DZO4Cfd',
    'container.build_id' => 'f2c4853e',
    'container.build_time' => 1549295997,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerDZO4Cfd');
