<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN7J4dXo\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN7J4dXo/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN7J4dXo.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN7J4dXo\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerN7J4dXo\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'N7J4dXo',
    'container.build_id' => '3a44fa14',
    'container.build_time' => 1549554763,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerN7J4dXo');
